// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: message/system.proto

package climsg

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CSHandshake with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CSHandshake) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CSHandshake with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CSHandshakeMultiError, or
// nil if none found.
func (m *CSHandshake) ValidateAll() error {
	return m.validate(true)
}

func (m *CSHandshake) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	// no validation rules for ServerId

	// no validation rules for Pub

	if len(errors) > 0 {
		return CSHandshakeMultiError(errors)
	}

	return nil
}

// CSHandshakeMultiError is an error wrapping multiple validation errors
// returned by CSHandshake.ValidateAll() if the designated constraints aren't met.
type CSHandshakeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CSHandshakeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CSHandshakeMultiError) AllErrors() []error { return m }

// CSHandshakeValidationError is the validation error returned by
// CSHandshake.Validate if the designated constraints aren't met.
type CSHandshakeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CSHandshakeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CSHandshakeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CSHandshakeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CSHandshakeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CSHandshakeValidationError) ErrorName() string { return "CSHandshakeValidationError" }

// Error satisfies the builtin error interface
func (e CSHandshakeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCSHandshake.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CSHandshakeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CSHandshakeValidationError{}

// Validate checks the field values on SCHandshake with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SCHandshake) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SCHandshake with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SCHandshakeMultiError, or
// nil if none found.
func (m *SCHandshake) ValidateAll() error {
	return m.validate(true)
}

func (m *SCHandshake) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for StartIndex

	// no validation rules for Key

	if len(errors) > 0 {
		return SCHandshakeMultiError(errors)
	}

	return nil
}

// SCHandshakeMultiError is an error wrapping multiple validation errors
// returned by SCHandshake.ValidateAll() if the designated constraints aren't met.
type SCHandshakeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SCHandshakeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SCHandshakeMultiError) AllErrors() []error { return m }

// SCHandshakeValidationError is the validation error returned by
// SCHandshake.Validate if the designated constraints aren't met.
type SCHandshakeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SCHandshakeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SCHandshakeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SCHandshakeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SCHandshakeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SCHandshakeValidationError) ErrorName() string { return "SCHandshakeValidationError" }

// Error satisfies the builtin error interface
func (e SCHandshakeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSCHandshake.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SCHandshakeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SCHandshakeValidationError{}

// Validate checks the field values on CSHeartBeat with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CSHeartBeat) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CSHeartBeat with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CSHeartBeatMultiError, or
// nil if none found.
func (m *CSHeartBeat) ValidateAll() error {
	return m.validate(true)
}

func (m *CSHeartBeat) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ClientTime

	if len(errors) > 0 {
		return CSHeartBeatMultiError(errors)
	}

	return nil
}

// CSHeartBeatMultiError is an error wrapping multiple validation errors
// returned by CSHeartBeat.ValidateAll() if the designated constraints aren't met.
type CSHeartBeatMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CSHeartBeatMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CSHeartBeatMultiError) AllErrors() []error { return m }

// CSHeartBeatValidationError is the validation error returned by
// CSHeartBeat.Validate if the designated constraints aren't met.
type CSHeartBeatValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CSHeartBeatValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CSHeartBeatValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CSHeartBeatValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CSHeartBeatValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CSHeartBeatValidationError) ErrorName() string { return "CSHeartBeatValidationError" }

// Error satisfies the builtin error interface
func (e CSHeartBeatValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCSHeartBeat.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CSHeartBeatValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CSHeartBeatValidationError{}

// Validate checks the field values on SCHeartBeat with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SCHeartBeat) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SCHeartBeat with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SCHeartBeatMultiError, or
// nil if none found.
func (m *SCHeartBeat) ValidateAll() error {
	return m.validate(true)
}

func (m *SCHeartBeat) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ServerTime

	// no validation rules for Code

	if len(errors) > 0 {
		return SCHeartBeatMultiError(errors)
	}

	return nil
}

// SCHeartBeatMultiError is an error wrapping multiple validation errors
// returned by SCHeartBeat.ValidateAll() if the designated constraints aren't met.
type SCHeartBeatMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SCHeartBeatMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SCHeartBeatMultiError) AllErrors() []error { return m }

// SCHeartBeatValidationError is the validation error returned by
// SCHeartBeat.Validate if the designated constraints aren't met.
type SCHeartBeatValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SCHeartBeatValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SCHeartBeatValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SCHeartBeatValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SCHeartBeatValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SCHeartBeatValidationError) ErrorName() string { return "SCHeartBeatValidationError" }

// Error satisfies the builtin error interface
func (e SCHeartBeatValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSCHeartBeat.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SCHeartBeatValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SCHeartBeatValidationError{}

// Validate checks the field values on SCServerUnknownErr with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SCServerUnknownErr) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SCServerUnknownErr with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SCServerUnknownErrMultiError, or nil if none found.
func (m *SCServerUnknownErr) ValidateAll() error {
	return m.validate(true)
}

func (m *SCServerUnknownErr) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Mod

	// no validation rules for Seq

	// no validation rules for Msg

	if len(errors) > 0 {
		return SCServerUnknownErrMultiError(errors)
	}

	return nil
}

// SCServerUnknownErrMultiError is an error wrapping multiple validation errors
// returned by SCServerUnknownErr.ValidateAll() if the designated constraints
// aren't met.
type SCServerUnknownErrMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SCServerUnknownErrMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SCServerUnknownErrMultiError) AllErrors() []error { return m }

// SCServerUnknownErrValidationError is the validation error returned by
// SCServerUnknownErr.Validate if the designated constraints aren't met.
type SCServerUnknownErrValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SCServerUnknownErrValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SCServerUnknownErrValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SCServerUnknownErrValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SCServerUnknownErrValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SCServerUnknownErrValidationError) ErrorName() string {
	return "SCServerUnknownErrValidationError"
}

// Error satisfies the builtin error interface
func (e SCServerUnknownErrValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSCServerUnknownErr.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SCServerUnknownErrValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SCServerUnknownErrValidationError{}

// Validate checks the field values on SCServerLogout with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SCServerLogout) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SCServerLogout with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SCServerLogoutMultiError,
// or nil if none found.
func (m *SCServerLogout) ValidateAll() error {
	return m.validate(true)
}

func (m *SCServerLogout) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	if len(errors) > 0 {
		return SCServerLogoutMultiError(errors)
	}

	return nil
}

// SCServerLogoutMultiError is an error wrapping multiple validation errors
// returned by SCServerLogout.ValidateAll() if the designated constraints
// aren't met.
type SCServerLogoutMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SCServerLogoutMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SCServerLogoutMultiError) AllErrors() []error { return m }

// SCServerLogoutValidationError is the validation error returned by
// SCServerLogout.Validate if the designated constraints aren't met.
type SCServerLogoutValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SCServerLogoutValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SCServerLogoutValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SCServerLogoutValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SCServerLogoutValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SCServerLogoutValidationError) ErrorName() string { return "SCServerLogoutValidationError" }

// Error satisfies the builtin error interface
func (e SCServerLogoutValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSCServerLogout.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SCServerLogoutValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SCServerLogoutValidationError{}
