// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: message/user.proto

package climsg

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserProto with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserProto with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserProtoMultiError, or nil
// if none found.
func (m *UserProto) ValidateAll() error {
	return m.validate(true)
}

func (m *UserProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetBasic()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserProtoValidationError{
					field:  "Basic",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserProtoValidationError{
					field:  "Basic",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBasic()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserProtoValidationError{
				field:  "Basic",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetStorage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserProtoValidationError{
					field:  "Storage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserProtoValidationError{
					field:  "Storage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStorage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserProtoValidationError{
				field:  "Storage",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetHeroList()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserProtoValidationError{
					field:  "HeroList",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserProtoValidationError{
					field:  "HeroList",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHeroList()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserProtoValidationError{
				field:  "HeroList",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetRoom()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserProtoValidationError{
					field:  "Room",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserProtoValidationError{
					field:  "Room",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRoom()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserProtoValidationError{
				field:  "Room",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UserProtoMultiError(errors)
	}

	return nil
}

// UserProtoMultiError is an error wrapping multiple validation errors returned
// by UserProto.ValidateAll() if the designated constraints aren't met.
type UserProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserProtoMultiError) AllErrors() []error { return m }

// UserProtoValidationError is the validation error returned by
// UserProto.Validate if the designated constraints aren't met.
type UserProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserProtoValidationError) ErrorName() string { return "UserProtoValidationError" }

// Error satisfies the builtin error interface
func (e UserProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserProtoValidationError{}

// Validate checks the field values on RechargeParamProto with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RechargeParamProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RechargeParamProto with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RechargeParamProtoMultiError, or nil if none found.
func (m *RechargeParamProto) ValidateAll() error {
	return m.validate(true)
}

func (m *RechargeParamProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProductId

	// no validation rules for Store

	// no validation rules for Payload

	if len(errors) > 0 {
		return RechargeParamProtoMultiError(errors)
	}

	return nil
}

// RechargeParamProtoMultiError is an error wrapping multiple validation errors
// returned by RechargeParamProto.ValidateAll() if the designated constraints
// aren't met.
type RechargeParamProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RechargeParamProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RechargeParamProtoMultiError) AllErrors() []error { return m }

// RechargeParamProtoValidationError is the validation error returned by
// RechargeParamProto.Validate if the designated constraints aren't met.
type RechargeParamProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RechargeParamProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RechargeParamProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RechargeParamProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RechargeParamProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RechargeParamProtoValidationError) ErrorName() string {
	return "RechargeParamProtoValidationError"
}

// Error satisfies the builtin error interface
func (e RechargeParamProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRechargeParamProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RechargeParamProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RechargeParamProtoValidationError{}

// Validate checks the field values on SCPushSyncUser with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SCPushSyncUser) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SCPushSyncUser with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SCPushSyncUserMultiError,
// or nil if none found.
func (m *SCPushSyncUser) ValidateAll() error {
	return m.validate(true)
}

func (m *SCPushSyncUser) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetUser()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SCPushSyncUserValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SCPushSyncUserValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SCPushSyncUserValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SCPushSyncUserMultiError(errors)
	}

	return nil
}

// SCPushSyncUserMultiError is an error wrapping multiple validation errors
// returned by SCPushSyncUser.ValidateAll() if the designated constraints
// aren't met.
type SCPushSyncUserMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SCPushSyncUserMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SCPushSyncUserMultiError) AllErrors() []error { return m }

// SCPushSyncUserValidationError is the validation error returned by
// SCPushSyncUser.Validate if the designated constraints aren't met.
type SCPushSyncUserValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SCPushSyncUserValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SCPushSyncUserValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SCPushSyncUserValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SCPushSyncUserValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SCPushSyncUserValidationError) ErrorName() string { return "SCPushSyncUserValidationError" }

// Error satisfies the builtin error interface
func (e SCPushSyncUserValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSCPushSyncUser.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SCPushSyncUserValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SCPushSyncUserValidationError{}

// Validate checks the field values on CSLogin with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CSLogin) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CSLogin with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in CSLoginMultiError, or nil if none found.
func (m *CSLogin) ValidateAll() error {
	return m.validate(true)
}

func (m *CSLogin) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Reconnect

	if len(errors) > 0 {
		return CSLoginMultiError(errors)
	}

	return nil
}

// CSLoginMultiError is an error wrapping multiple validation errors returned
// by CSLogin.ValidateAll() if the designated constraints aren't met.
type CSLoginMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CSLoginMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CSLoginMultiError) AllErrors() []error { return m }

// CSLoginValidationError is the validation error returned by CSLogin.Validate
// if the designated constraints aren't met.
type CSLoginValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CSLoginValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CSLoginValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CSLoginValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CSLoginValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CSLoginValidationError) ErrorName() string { return "CSLoginValidationError" }

// Error satisfies the builtin error interface
func (e CSLoginValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCSLogin.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CSLoginValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CSLoginValidationError{}

// Validate checks the field values on SCLogin with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SCLogin) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SCLogin with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in SCLoginMultiError, or nil if none found.
func (m *SCLogin) ValidateAll() error {
	return m.validate(true)
}

func (m *SCLogin) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for ServerTime

	if all {
		switch v := interface{}(m.GetUser()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SCLoginValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SCLoginValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SCLoginValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Created

	if len(errors) > 0 {
		return SCLoginMultiError(errors)
	}

	return nil
}

// SCLoginMultiError is an error wrapping multiple validation errors returned
// by SCLogin.ValidateAll() if the designated constraints aren't met.
type SCLoginMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SCLoginMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SCLoginMultiError) AllErrors() []error { return m }

// SCLoginValidationError is the validation error returned by SCLogin.Validate
// if the designated constraints aren't met.
type SCLoginValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SCLoginValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SCLoginValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SCLoginValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SCLoginValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SCLoginValidationError) ErrorName() string { return "SCLoginValidationError" }

// Error satisfies the builtin error interface
func (e SCLoginValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSCLogin.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SCLoginValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SCLoginValidationError{}

// Validate checks the field values on CSUpdateName with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CSUpdateName) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CSUpdateName with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CSUpdateNameMultiError, or
// nil if none found.
func (m *CSUpdateName) ValidateAll() error {
	return m.validate(true)
}

func (m *CSUpdateName) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return CSUpdateNameMultiError(errors)
	}

	return nil
}

// CSUpdateNameMultiError is an error wrapping multiple validation errors
// returned by CSUpdateName.ValidateAll() if the designated constraints aren't met.
type CSUpdateNameMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CSUpdateNameMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CSUpdateNameMultiError) AllErrors() []error { return m }

// CSUpdateNameValidationError is the validation error returned by
// CSUpdateName.Validate if the designated constraints aren't met.
type CSUpdateNameValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CSUpdateNameValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CSUpdateNameValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CSUpdateNameValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CSUpdateNameValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CSUpdateNameValidationError) ErrorName() string { return "CSUpdateNameValidationError" }

// Error satisfies the builtin error interface
func (e CSUpdateNameValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCSUpdateName.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CSUpdateNameValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CSUpdateNameValidationError{}

// Validate checks the field values on SCUpdateName with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SCUpdateName) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SCUpdateName with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SCUpdateNameMultiError, or
// nil if none found.
func (m *SCUpdateName) ValidateAll() error {
	return m.validate(true)
}

func (m *SCUpdateName) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for IsIllegal

	if len(errors) > 0 {
		return SCUpdateNameMultiError(errors)
	}

	return nil
}

// SCUpdateNameMultiError is an error wrapping multiple validation errors
// returned by SCUpdateName.ValidateAll() if the designated constraints aren't met.
type SCUpdateNameMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SCUpdateNameMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SCUpdateNameMultiError) AllErrors() []error { return m }

// SCUpdateNameValidationError is the validation error returned by
// SCUpdateName.Validate if the designated constraints aren't met.
type SCUpdateNameValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SCUpdateNameValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SCUpdateNameValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SCUpdateNameValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SCUpdateNameValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SCUpdateNameValidationError) ErrorName() string { return "SCUpdateNameValidationError" }

// Error satisfies the builtin error interface
func (e SCUpdateNameValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSCUpdateName.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SCUpdateNameValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SCUpdateNameValidationError{}

// Validate checks the field values on CSSetGender with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CSSetGender) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CSSetGender with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CSSetGenderMultiError, or
// nil if none found.
func (m *CSSetGender) ValidateAll() error {
	return m.validate(true)
}

func (m *CSSetGender) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Gender

	if len(errors) > 0 {
		return CSSetGenderMultiError(errors)
	}

	return nil
}

// CSSetGenderMultiError is an error wrapping multiple validation errors
// returned by CSSetGender.ValidateAll() if the designated constraints aren't met.
type CSSetGenderMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CSSetGenderMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CSSetGenderMultiError) AllErrors() []error { return m }

// CSSetGenderValidationError is the validation error returned by
// CSSetGender.Validate if the designated constraints aren't met.
type CSSetGenderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CSSetGenderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CSSetGenderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CSSetGenderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CSSetGenderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CSSetGenderValidationError) ErrorName() string { return "CSSetGenderValidationError" }

// Error satisfies the builtin error interface
func (e CSSetGenderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCSSetGender.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CSSetGenderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CSSetGenderValidationError{}

// Validate checks the field values on SCSetGender with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SCSetGender) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SCSetGender with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SCSetGenderMultiError, or
// nil if none found.
func (m *SCSetGender) ValidateAll() error {
	return m.validate(true)
}

func (m *SCSetGender) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	if len(errors) > 0 {
		return SCSetGenderMultiError(errors)
	}

	return nil
}

// SCSetGenderMultiError is an error wrapping multiple validation errors
// returned by SCSetGender.ValidateAll() if the designated constraints aren't met.
type SCSetGenderMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SCSetGenderMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SCSetGenderMultiError) AllErrors() []error { return m }

// SCSetGenderValidationError is the validation error returned by
// SCSetGender.Validate if the designated constraints aren't met.
type SCSetGenderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SCSetGenderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SCSetGenderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SCSetGenderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SCSetGenderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SCSetGenderValidationError) ErrorName() string { return "SCSetGenderValidationError" }

// Error satisfies the builtin error interface
func (e SCSetGenderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSCSetGender.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SCSetGenderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SCSetGenderValidationError{}
