// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: gate/intra/v1/auth.proto

package intrav1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AuthToken with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AuthToken) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthToken with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AuthTokenMultiError, or nil
// if none found.
func (m *AuthToken) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthToken) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Location

	// no validation rules for AccountId

	// no validation rules for Rand

	// no validation rules for Timeout

	// no validation rules for Unencrypted

	// no validation rules for Color

	// no validation rules for Status

	if len(errors) > 0 {
		return AuthTokenMultiError(errors)
	}

	return nil
}

// AuthTokenMultiError is an error wrapping multiple validation errors returned
// by AuthToken.ValidateAll() if the designated constraints aren't met.
type AuthTokenMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthTokenMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthTokenMultiError) AllErrors() []error { return m }

// AuthTokenValidationError is the validation error returned by
// AuthToken.Validate if the designated constraints aren't met.
type AuthTokenValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthTokenValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthTokenValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthTokenValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthTokenValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthTokenValidationError) ErrorName() string { return "AuthTokenValidationError" }

// Error satisfies the builtin error interface
func (e AuthTokenValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthToken.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthTokenValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthTokenValidationError{}
